config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#home"

  get "resume", to: "home#resume", as: "resume"
  get "about", to: "home#about", as: "about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end

  def resume
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Som Akudu | About</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" integrity="sha256-46qynGAkLSFpVbEBog43gvNhfrOj+BmwXdxFgVK/Kvc=" crossorigin="anonymous" />
    <link rel="preconnect" href="https://rsms.me/">
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
  </head>
  <body>
  <header></header>
    <!-- Introduction -->
    <section class="about-container">
      <div class="mural-container">
        <div class="top-back">
          <div class="container-top">
            <div class="about-slogan">
              <div class="slogan">
                <h1 class=slogan-title><strong class="about-name">Hey, I'm Som.</strong><br>I'm a <u>Fullstack <br>Developer</u> based out <br>of London, UK.</h1>
                <p class="btn-about"><a href="mailto:somakudu@gmail.com?subject=Hello!" target="_blank"><strong>Get in touch →</strong></a></p>
              </div>
            </div>
          </div>
        </div>
        <div class="container-middle">
          <div class="container-left">
            <div class="som-detes">
              <div class="background">
                <div class="about-profile">
                <%= cl_image_tag "present", height: 300, width: 220 %>
                <h3>About</h3>
                <p class="som-about">I'm a Pharmacist turned Fullstack Developer. I was born and raised in NW London (and also raised in Radlett, a village outside of London).</p>
                <p class="som-about">When I'm not coding, I'm either watching anime or dabbling in illustration and oil painting. If you like my site, don't hesitate to <a href="mailto:somakudu@gmail.com?subject=Hello!" target="_blank"><strong>reach out!</strong></a></p>
                </div>
                <div class="icon-img">
                  <i class="fa-solid fa-palette"></i>
                </div>
                <div class="about-profile">
                <%= cl_image_tag "soho", height: 300, width: 230 %>
                <h3>Communities</h3>
                <p class="som-about">Ever since completing my coding bootcamp, I have been an active member of <a href="https://www.lewagon.com/london" target="_blank"><strong>Le Wagon London</strong></a> where I teach other people part-time how to code. It is an incredible and diverse community that has been a rewarding part of my coding journey.</p>
                <p class="som-about" >I am also currently taking part of the <a href="https://www.blackgirlsintech.org/mentoring-programme" target="_blank"><strong>Black Girls in Tech</strong></a> Mentorship Programme where I meet other black women in tech to talk all things tech. <a href="https://codebar.io/" target="_blank"><strong>Code Bar</strong></a> is another community who's programming workshops I attend.</p>
                </div>
              </div>

              <div class="pictures">
                <div class="about-profile">
                <div class="icon-img">
                  <i class="fa-solid fa-laptop"></i>
                </div>
                <%= cl_image_tag "som-ilo", height: 300, width: 230 %>
                <%= cl_image_tag "exhibit", height: 300, width: 230 %>
                </div>
                <div class="icon-img">
                  <i class="fa-solid fa-headphones"></i>
                </div>
                <%= cl_image_tag "fitz", height: 300, width: 230 %>
              </div>
            </div>
          </div>

          <div class="container-right">
            <div class="likes">
              <div class="about-profile">
              <h3>What I Like</h3>
              <p class="som-about">As well as coding in my spare time, I like...</p>
              <p class="som-about">Freshly baked melted chocolate brownies with banana split ice-cream from <a href="https://www.instagram.com/thepuddingstop/" target="_blank"><strong>The Pudding Stop</strong></a>.</p>
              <p class="som-about">Obssessed with all things Anime (<a href="https://www.crunchyroll.com/series/GRMG8ZQZR/one-piece" target="_blank"><strong>One Piece</strong></a> is my fave!).</p>
              <p class="som-about">Gallery visits and art exhibitions, especially at the <a href="https://www.tate.org.uk/visit/tate-modern" target="_blank"><strong>Tate Modern</strong></a>.</p>
              </div>
              <div class="icon-img">
                <i class="fa-solid fa-earth-africa"></i>
              </div>
              <%= cl_image_tag "sunflower", height: 300, width: 230 %>
              <div class="about-profile">
              </div>
              <%= cl_image_tag "plant-ilo", height: 300, width: 230 %><div class="about-profile">
              </div>
              <div class="icon-img">
                <i class="fa-solid fa-bolt"></i>
              </div>
              <%= cl_image_tag "gallery", height: 300, width: 230 %>
            </div>
            <div class="learning">
              <%= cl_image_tag "still", height: 290, width: 230 %>
              <div class="about-profile">
              <h3>What I'm Learning</h3>
              <p class="som-about"><a href="https://www.youtube.com/playlist?list=PLTzMGnJjrsSy6H8uiX3XKWtUhhj2Vilw1" target="_blank"><strong>Gordon Ramsey's</strong></a> 10 minute meals (which usally takes me 30 minutes).</p>
              <p class="som-about">Recently got into <a><strong>Brazilian Forro</strong></a>, which is like Salsa.</p>
              <p class="som-about">Illustrations and animations on <a><strong>Procreate</strong></a>.</p>
              </div>
              <div class="icon-img">
                <i class="fa-solid fa-dumbbell"></i>
              </div>
              <%= cl_image_tag "sketch", height: 300, width: 230 %>
              <div class="about-profile">
              </div>
              <%= cl_image_tag "gaia", height: 300, width: 230 %>
            </div>
          </div>
        </div>
      </div>
      <div class="video-container">
      </div>
    </section>
  </body>
</html>

app/views/home/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Som Akudu</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" integrity="sha256-46qynGAkLSFpVbEBog43gvNhfrOj+BmwXdxFgVK/Kvc=" crossorigin="anonymous" />
    <link rel="preconnect" href="https://rsms.me/">
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
  </head>
  <body>
    <header>
    </header>
    <!-- Introduction -->
    <section class="container-portfolio">
      <div class="top-back">
        <div class="section-title">
          <div class="profile-img-section">
            <%= cl_image_tag "som", height: 300, width: 230 %>
          </div>
          <div class="slogan">
            <h1 >
              <strong class="name">Hey, I'm Som.</strong><br>I'm a <u>Fullstack <br>Developer</u> based out <br>of London, UK.
            </h1>
            <h6 class="btn-simple"><a href="mailto:somakudu@gmail.com?subject=Hello!" target="_blank"><strong>Get in touch →</strong></a></h6>
          </div>
        </div>
      </div>
    </section>
    <!-- Portfolio -->
    <section class=portfolio-back>
      <div class="portfolio-section">
        <div>
          <a href="https://www.scanher.co.uk/" target="_blank">
            <h2 class="project-name">scan<em>Her</em></h2>
            <p class="project-tags">Product, Web, Branding, Healthtech</p>
            <div class="project-card">
              <%= cl_image_tag "scanher", height: 310, width: 505 %>
            </div>
          </a>
        </div>
        <div>
          <a href="https://github.com/AranSeehra/gyota" target="_blank">
            <h2 class="project-name">Get Your Own Teaching Assistant</h2>
            <p class="project-tags">Web, Edtech</p>
            <div class="project-card">
              <%= cl_image_tag "gyota", height: 310, width: 505 %>
            </div>
          </a>
        </div>
        <div>
          <a href="https://github.com/somunachima/rails-watch-list" target="_blank">
            <h2 class="project-name">Movie Watchlist</h2>
            <p class="project-tags">Web, Entertainment</p>
            <div class="project-card-movie">
              <i class="fa-solid fa-clapperboard"></i>
            </div>
          </a>
        </div>
        <div>
          <a href="https://github.com/somunachima/rails-yelp-mvp" target="_blank">
            <h2 class="project-name">Yelp Clone</h2>
            <p class="project-tags">Lifestyle</p>
            <div class="project-card">
              <%= cl_image_tag "yelp", height: 330, width: 505 %>
            </div>
          </a>
        </div>
        <div>
          <a href="https://github.com/somunachima/rails-task-manager" target="_blank">
            <h2 class="project-name">Task Manager</h2>
            <p class="project-tags">Lifestyle</p>
            <div class="project-card-task">
              <i class="fa-solid fa-clipboard-list"></i>
            </div>
          </a>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <%= render "shared/navbar" %>
    <%= yield %>
  <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <%# <a href="https://www.youtube.com/@LeWagon"><i class="fa-brands fa-youtube"></i></a> %>
    <a href="https://github.com/somunachima/" target="_blank"><i class="fab fa-github"></i></a>
    <%# <a href="https://www.instagram.com/scanher_/"><i class="fab fa-instagram"></i></a> %>
    <%# <a href="https://en-gb.facebook.com/lewagon/"><i class="fab fa-facebook"></i></a> %>
    <%# <a href="https://twitter.com/lewagonlondon"><i class="fab fa-twitter"></i></a> %>
    <a href="https://www.linkedin.com/in/somakudu/" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <p>This website is made with <i class="fas fa-heart"></i> by Som</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "Som_Logo.png" %>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active"><a href="home.html" class="nav__link"><%= link_to "Home", root_path, class: "nav-link" %></a></li>
        <li class="nav-item active"><a href="about.html" class="nav__link"><%= link_to "About", about_path, class: "nav-link" %></a></li>
        <li class="nav-item active"><a href="resume.html" class="nav__link"><%= link_to "Resume", resume_path, class: "nav-link" %></a></li>
        <li class="nav-item active" id="email"><a href="mailto:somakudu@gmail.com?subject=Hello!" class="nav__link" target="_blank">Contact</a></li>
        <li class="nav-item active"><a href="https://www.linkedin.com/in/somakudu/" class="nav__link" target="_blank"><i class="fab fa-linkedin"></i></li>
        <li class="nav-item active"><a href="https://github.com/somunachima/" class="nav__link" target="_blank"><i class="fab fa-github"></i></a></li>

      </ul>
    </div>
  </div>
</div>